"""Update Activity model, Remove student_activity helper table

Revision ID: 1753ead768f9
Revises: e427bf354482
Create Date: 2021-01-22 13:25:08.941330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1753ead768f9'
down_revision = 'e427bf354482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_activity')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_activity_student_id'), ['student_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_activity_student_id_student'), 'student', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_activity_student_id_student'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_activity_student_id'))
        batch_op.drop_column('student_id')

    op.create_table('student_activity',
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('activity_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name='fk_student_activity_activity_id_activity'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='fk_student_activity_student_id_student')
    )
    # ### end Alembic commands ###
