"""Comment out date-related fields

Revision ID: 228e975fd2df
Revises: abe0e1ab4a0b
Create Date: 2021-07-14 16:56:11.833481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228e975fd2df'
down_revision = 'abe0e1ab4a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_activity_date')
        batch_op.drop_column('activity_date')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index('ix_attendance_attendance_date')
        batch_op.drop_column('attendance_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_date', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.create_index('ix_attendance_attendance_date', ['attendance_date'], unique=False)

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_date', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.create_index('ix_activity_activity_date', ['activity_date'], unique=False)

    # ### end Alembic commands ###
