"""empty message

Revision ID: 2cfeb4a56522
Revises: 
Create Date: 2021-07-13 18:40:29.492007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cfeb4a56522'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_activity_status'), ['status'], unique=False)
        batch_op.drop_index('ix_activity_test')
        batch_op.drop_index('ix_activity_test2')
        batch_op.drop_column('test')
        batch_op.drop_column('test2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test2', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('test', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_index('ix_activity_test2', ['test2'], unique=False)
        batch_op.create_index('ix_activity_test', ['test'], unique=False)
        batch_op.drop_index(batch_op.f('ix_activity_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
