"""empty message

Revision ID: 5ad1dca7adf8
Revises: 756f94c9fab1
Create Date: 2021-01-22 17:11:38.956840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad1dca7adf8'
down_revision = '756f94c9fab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_attendance_user_id'), ['user_id'], unique=False)
        batch_op.drop_index('ix_attendance_attendance_status')
        batch_op.create_foreign_key(batch_op.f('fk_attendance_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('attendance_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_status', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_attendance_user_id_user'), type_='foreignkey')
        batch_op.create_index('ix_attendance_attendance_status', ['attendance_status'], unique=False)
        batch_op.drop_index(batch_op.f('ix_attendance_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
