"""Add subject_number field to user table

Revision ID: 9f186a745147
Revises: d422cfabb7b3
Create Date: 2021-07-17 13:45:38.408340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f186a745147'
down_revision = 'd422cfabb7b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_number', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_subject_number'), ['subject_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_subject_number'))
        batch_op.drop_column('subject_number')

    # ### end Alembic commands ###
