"""Initialize postgres db

Revision ID: c02659cb3ba6
Revises: 
Create Date: 2021-07-13 15:44:00.158948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02659cb3ba6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('student_number', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_student_number'), ['student_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_student_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student'))
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_student_name'), ['student_name'], unique=False)

    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subject_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_subject_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject'))
    )
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_subject_name'), ['subject_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_subject_user_id'), ['user_id'], unique=False)

    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resources', sa.Text(), nullable=True),
    sa.Column('activity_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_activity_student_id_student')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_activity_subject_id_subject')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_activity_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity'))
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_activity_date'), ['activity_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_notes'), ['notes'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_resources'), ['resources'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_user_id'), ['user_id'], unique=False)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('attendance_date', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_attendance_student_id_student')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_attendance_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance'))
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_attendance_date'))

    op.drop_table('attendance')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_title'))
        batch_op.drop_index(batch_op.f('ix_activity_subject_id'))
        batch_op.drop_index(batch_op.f('ix_activity_student_id'))
        batch_op.drop_index(batch_op.f('ix_activity_status'))
        batch_op.drop_index(batch_op.f('ix_activity_resources'))
        batch_op.drop_index(batch_op.f('ix_activity_notes'))
        batch_op.drop_index(batch_op.f('ix_activity_description'))
        batch_op.drop_index(batch_op.f('ix_activity_activity_date'))

    op.drop_table('activity')
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_user_id'))
        batch_op.drop_index(batch_op.f('ix_subject_subject_name'))

    op.drop_table('subject')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_student_name'))

    op.drop_table('student')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_student_number'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
