"""Add user_subject helper table, Change subject-activity relationship to one-to-many, Change user-subject relationship to many-to-many

Revision ID: c6e67fd8342d
Revises: de505fcc11d8
Create Date: 2021-01-18 19:00:28.933106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e67fd8342d'
down_revision = 'de505fcc11d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_subject',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['subject.id'], name=op.f('fk_user_subject_activity_id_subject')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_subject_user_id_user'))
    )
    op.drop_table('subject_activity')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_activity_subject_id'), ['subject_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_activity_subject_id_subject'), 'subject', ['subject_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_activity_subject_id_subject'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_activity_subject_id'))
        batch_op.drop_column('subject_id')

    op.create_table('subject_activity',
    sa.Column('subject_id', sa.INTEGER(), nullable=True),
    sa.Column('activity_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name='fk_subject_activity_activity_id_activity'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name='fk_subject_activity_subject_id_subject')
    )
    op.drop_table('user_subject')
    # ### end Alembic commands ###
