"""Test TIMESTAMP column type

Revision ID: d422cfabb7b3
Revises: 228e975fd2df
Create Date: 2021-07-14 16:58:13.107808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd422cfabb7b3'
down_revision = '228e975fd2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_date', sa.TIMESTAMP(timezone=False), nullable=False))
        batch_op.create_index(batch_op.f('ix_activity_activity_date'), ['activity_date'], unique=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_date', sa.TIMESTAMP(timezone=False), nullable=False))
        batch_op.create_index(batch_op.f('ix_attendance_attendance_date'), ['attendance_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_attendance_date'))
        batch_op.drop_column('attendance_date')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_activity_date'))
        batch_op.drop_column('activity_date')

    # ### end Alembic commands ###
