"""Update User model

Revision ID: e427bf354482
Revises: c6e67fd8342d
Create Date: 2021-01-20 22:41:54.429419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e427bf354482'
down_revision = 'c6e67fd8342d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_activity_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_activity_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_activity_user_id_user'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_activity_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
