"""Comment out test date fields

Revision ID: e5349fcdcb89
Revises: 5784c3175a3f
Create Date: 2021-07-13 21:16:02.822488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5349fcdcb89'
down_revision = '5784c3175a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_activity_date2')
        batch_op.drop_column('activity_date2')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index('ix_attendance_attendance_date2')
        batch_op.drop_column('attendance_date2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_date2', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.create_index('ix_attendance_attendance_date2', ['attendance_date2'], unique=False)

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_date2', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.create_index('ix_activity_activity_date2', ['activity_date2'], unique=False)

    # ### end Alembic commands ###
